module.exports = {
  testEnvironment: 'node',
  testMatch: [
    '**/?(*.)test.ts',
  ],
  moduleFileExtensions: [
    'js',  // not used directly, but MANDATORY
    'ts',  // actually used
  ],
  transform: {
    // Transform .ts files, and also .js ones generated by TypeScript, which scripts load -
    // https://github.com/microsoft/TypeScript/issues/18442#issuecomment-581738714
    '^.+\\.(ts|js)$': 'babel-jest',
  },
};
